# test agains node
environment:
  matrix:
    - nodejs_version: "6"

# install scripts (runs after repo cloning)
install:
  # get the latest stable node.js
  - ps: Install-Product node $env:nodejs_version
  - npm install

# post install test scripts
test_script:
  # output useful for debugging

  - node --version
  - npm --version

  - npm test

# dont' actually build
build: off
